repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
        stages: [commit]
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        args: [--in-place, --pre-summary-newline, --close-quotes-on-newline]
        stages: [commit]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.2.0
    hooks:
    -   id: pyupgrade
        args: [--py310-plus]
        stages: [commit]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.2
    hooks:
      - id: pycln
        args: [-q, --all, --exclude, __init__.py]
        stages: [commit]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [--profile, black]
        stages: [commit]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        stages: [commit]
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        name: Check PEP8
        args: [--max-line-length, "88"]
        stages: [commit]
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push]
  - repo: local
    hooks:
      - id: git
        name: git
        entry: git update-index --again
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
  - repo: local
    hooks:
    -   id: publish
        name: publish on pypi
        language: system
        entry: publish
        pass_filenames: false
        always_run: true
